#!/usr/bin/env bash
# The second share of the supervision-host behavior suite, split out of
# tests/fm-supervision-host.test.sh so the portable serial lane can schedule the
# suite's ~26 minutes of real-process cases across two CI shards instead of one
# script pressing against the job cap. See docs/fm-test-portable-shards.md
# "Portable serial CI shards" for the layout owner.
#
# That file owns the shared fixture, every helper, and the first share of the
# cases. Sourcing it defines the fixture and cases without running its own
# share, which only runs on direct execution. Every case here is defined there.
# shellcheck source=tests/fm-supervision-host.test.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-supervision-host.test.sh"

test_claude_stop_hook_restores_handoff_when_successor_closed_mid_engine_turn
test_claude_stop_hook_notifies_when_closed_successor_downtime_restore_fails
test_park_exit_probe_uses_half_second_child_sleeps
test_branch_outcomes_only_on_a_host_home_off_pi
test_branch_outcomes_collapse_repeated_captain_outcomes_per_task
test_branch_outcomes_budgets_count_bytes
test_branch_outcomes_stay_unread_when_a_projection_fails
test_branch_outcomes_stay_unread_when_the_drain_cannot_print
test_branch_outcomes_date_a_legacy_backlog_without_adopting_it
test_branch_ack_keeps_older_keyed_decision_open
test_branch_outcomes_date_an_outcome_carried_across_a_switch_off_pi
test_branch_outcomes_keep_an_unshown_outcome_until_acknowledged
test_branch_outcomes_keep_a_drain_presented_outcome_across_an_index_repair
test_attended_captain_outcome_reaches_main_through_branch_outcomes
test_quiet_record_without_its_daemon_is_a_present_captain
test_attended_close_with_unidentified_main_session_passes_to_main
test_close_accepted_away_that_turns_attended_passes_to_main
test_claude_stop_hook_delivers_a_main_only_pass_through
test_claude_stop_hook_runs_the_host_without_the_file_and_off_opts_out
test_successor_close_during_main_turn_is_delivered_at_the_next_turn_end
test_a_park_stopped_mid_take_over_leaves_the_take_over_to_the_next_park
test_primary_without_a_verified_mirror_runs_away_only
test_undelivered_dialog_is_fed_again_on_the_next_turn
test_large_turn_relays_an_early_visible_outcome
test_outcome_after_the_return_survives_a_host_killed_at_the_turn_end
test_report_without_acknowledgement_hands_the_wake_to_main
test_incomplete_engine_result_hands_the_wake_to_main
test_latch_keeps_attended_closes_on_main_and_skips_unopted_homes
test_attended_latch_keeps_closes_on_main_and_records_recovery_off_main
test_park_limit_lets_a_turn_outlive_the_boundary
test_unchanged_held_outcome_reaches_the_captain_once_until_a_new_event
